version: "3.8"

services:
  db:
    image: postgres:15
    container_name: go_project_db
    restart: always
    environment:
      POSTGRES_DB: DataBase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: