version: "3.8"

services:
  test_db:
    image: postgres:15
    container_name: go_project_test_db
    restart: always
    environment:
      POSTGRES_DB: TestDataBase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data: